name: Build, Publish, Redeploy Development

on:
  push:
    branches:
    - dev

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Set variables
        run: |
          ls
          VER=$(cat version)
          echo "VERSION=$VER" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sc4n1a471
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            sc4n1a471/car-thingy_python:${{ env.VERSION }}
            sc4n1a471/car-thingy_python:latest

  redeploy:
    name: Redeploying on development server
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Set variables
        run: |
          ls
          VER=$(cat version)
          echo "VERSION=$VER" >> $GITHUB_ENV
      -
        name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          body: '{ "version": "${{ env.VERSION  }}", "env": "dev" }'
